print("\n GRUPO DE TRABAJO ")
print("En un pueblo muy lejano del cual el nombre no puedo acordarme,")
print("existieron 5 compañeros, cada uno con un talento único")
print("que lo hacía sumamente útil para realizar cualquier actividad colaborativa.")
print("Entre ellos se encontraba David, con su poder de captación rápida;")
print("este poder le permitía aprender e imitar procedimientos de forma muy rápida.")
print("Esta habilidad era ideal para poder avanzar rápido en la realización de las actividades.")
print("Se cuenta que un día realizó una actividad grupal en menos de 24 horas.")
print("También estaba...")
print("También estaba María, una compañera tranquila y siempre dispuesta a colaborar.")
print("No era de hablar mucho, pero cuando llegaba el momento de trabajar, siempre aportaba algo útil.")
print("Mientras David aprendía rápido, María ayudaba a mantener el orden y la calma en el grupo.")
print("Gracias a eso, las ideas comenzaban a encajar como piezas de un rompecabezas.")
print("Un día, mientras realizaban una actividad importante, apareció un reto inesperado.")
print("Nadie sabía exactamente cómo resolverlo al principio.")
print("Pero entre todos comenzaron a pensar, aportar ideas y ayudarse unos a otros.")
print("Cada talento parecía tener un propósito dentro del equipo.")
print("Y aunque el camino no siempre era fácil, el grupo seguía avanzando con entusiasmo.")
print("Lo que ellos aún no sabían era que los otros tres compañeros también tenían habilidades sorprendentes...")
print("y muy pronto sería su turno de demostrar que en ese grupo nadie era menos importante.")