print("\n GRUPO DE TRABAJO ")
print("En un pueblo muy lejano del cual el nombre no puedo acordarme,")
print("existieron 5 compañeros, cada uno con un talento único")
print("que lo hacía sumamente útil para realizar cualquier actividad colaborativa.")
print("Entre ellos se encontraba David, con su poder de captación rápida;")
print("este poder le permitía aprender e imitar procedimientos de forma muy rápida.")
print("Esta habilidad era ideal para poder avanzar rápido en la realización de las actividades.")
print("Se cuenta que un día realizó una actividad grupal en menos de 24 horas.")
print("También estaba...")